name: Lint

on:
  pull_request:
    branches: [main]

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: yarn install
        run: yarn install
      - name: run ESLint
        uses: icrawl/action-eslint@v1
        with:
          custom-glob: "./**/*.ts"
