name: Lint
on:
  pull_request:
    branches: [main]

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v14
        uses: actions/setup-node@v1
        with:
          node-version: "14.15.1"
      - name: yarn install
        run: yarn install
      - name: eslint
        uses: icrawl/action-eslint@v1
