name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: |
          touch .env
          echo "EMAIL=${{secrets.EMAIL}}" >> .env
          echo "PASSWORD=${{secrets.PASSWORD}}" >> .env
          echo "TYPE=${{secrets.TYPE}}" >> .env
          echo "TOKEN_URI=${{secrets.TOKEN_URI}}" >> .env
          echo "PROJECT_ID=${{secrets.PROJECT_ID}}" >> .env
          echo "PRIVATE_KEY_ID=${{secrets.PRIVATE_KEY_ID}}" >> .env
          echo "PRIVATE_KEY=${{secrets.PRIVATE_KEY}}" >> .env
          echo "CLIENT_X509_CERT_URL=${{secrets.CLIENT_X509_CERT_URL}}" >> .env
          echo "CLIENT_ID=${{secrets.CLIENT_ID}}" >> .env
          echo "CLIENT_EMAIL=${{secrets.CLIENT_EMAIL}}" >> .env
          echo "AUTH_URI=${{secrets.AUTH_URI}}" >> .env
          echo "AUTH_PROVIDER_X509_CERT_URL=${{secrets.AUTH_PROVIDER_X509_CERT_URL}}" >> .env
    - run: npm test
  run-eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check ESLint Error
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.SECRET_KEY }}
          reporter: github-pr-check
          fail_on_error: true
      - name: Check ESLint Review
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.SECRET_KEY }}
          reporter: github-pr-review
          fail_on_error: true
