name: ci

on:
  pull_request_target:
    types: [labeled]

jobs:
  test:

    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: |
          touch .env
          echo "TYPE=${{secrets.TYPE}}" >> .env
          echo "TOKEN_URI=${{secrets.TOKEN_URI}}" >> .env
          echo "PROJECT_ID=${{secrets.PROJECT_ID}}" >> .env
          echo "PRIVATE_KEY_ID=${{secrets.PRIVATE_KEY_ID}}" >> .env
          echo "PRIVATE_KEY=${{secrets.PRIVATE_KEY}}" >> .env
          echo "CLIENT_X509_CERT_URL=${{secrets.CLIENT_X509_CERT_URL}}" >> .env
          echo "CLIENT_ID=${{secrets.CLIENT_ID}}" >> .env
          echo "CLIENT_EMAIL=${{secrets.CLIENT_EMAIL}}" >> .env
          echo "AUTH_URI=${{secrets.AUTH_URI}}" >> .env
          echo "AUTH_PROVIDER_X509_CERT_URL=${{secrets.AUTH_PROVIDER_X509_CERT_URL}}" >> .env
          echo "WEB_API_KEY=${{secrets.WEB_API_KEY}}" >> .env
          echo "PUBLIC_ENCRYPTION_KEY=${{secrets.PUBLIC_ENCRYPTION_KEY}}" >> .env
          echo "PUBLIC_ENCRYPTION_IV=${{secrets.PUBLIC_ENCRYPTION_IV}}" >> .env
    - run: npm test
